select distinct rt.tbamessage_header_platforminternalid as participant_id,
current_date as record_start_date,
'9999-09-09' as record_end_date,
1 as current_indicator,
hash(rt.tbamessage_header_platforminternalid,rt.tbamessage_header_nationaltaxid,rt.tbamessage_person_birthdate,tbwabcoc.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes_val_value,tbpavaa.tbamessage_personattributes_val_additionalattributes_val_fieldvalue,tbwabcs.tbamessage_benefitsworkerattributes_val_benefitscurrentemploymentstatuses_val_value) as Hashkey,
current_date create_date,
current_date as update_date,
'glue' as update_userid,
null as participant_name,
rt.tbamessage_header_nationaltaxid ssn,
rt.tbamessage_person_birthdate as birth_date,
case   tbwabcoc.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes_val_organizationid 
WHEN 8337 THEN tbwabcoc.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes_val_value
WHEN 8347 THEN tbwabcoc.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes_val_value ELSE null END department_code,
case   tbwabcoc.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes_val_organizationid 
WHEN 8357 THEN tbwabcoc.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes_val_value
WHEN 8367 THEN tbwabcoc.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes_val_value ELSE null END employer_agency_code,
case tbpavaa.tbamessage_personattributes_val_additionalattributes_val_fieldname
WHEN 'C-PAYROLL-OFF-NUM' THEN tbpavaa.tbamessage_personattributes_val_additionalattributes_val_fieldvalue
WHEN 'U-PAYROLL-OFF-NUM' THEN tbpavaa.tbamessage_personattributes_val_additionalattributes_val_fieldvalue
ELSE null end payroll_office_number,
case   tbwabcoc.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes_val_organizationid 
WHEN 8377 THEN tbwabcoc.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes_val_value
WHEN 8387 THEN tbwabcoc.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes_val_value ELSE null END personnel_office_indicator,
case   tbwabcs.tbamessage_benefitsworkerattributes_val_benefitscurrentemploymentstatuses_val_categoryid
WHEN 21 THEN tbwabcs.tbamessage_benefitsworkerattributes_val_benefitscurrentemploymentstatuses_val_value
WHEN 22 THEN tbwabcs.tbamessage_benefitsworkerattributes_val_benefitscurrentemploymentstatuses_val_value ELSE null END employment_code,
case   tbwabcs.tbamessage_benefitsworkerattributes_val_benefitscurrentemploymentstatuses_val_categoryid
WHEN 21 THEN tbwabcs.tbamessage_benefitsworkerattributes_val_benefitscurrentemploymentstatuses_val_begindate
WHEN 22 THEN tbwabcs.tbamessage_benefitsworkerattributes_val_benefitscurrentemploymentstatuses_val_begindate ELSE null END empployment_code_effective_date
from default.json_out_new_root rt left outer join default.json_out_new_root_tbamessage_benefitsworkerattributes tbwa
on rt.tbamessage_benefitsworkerattributes=tbwa.id left outer join 
default.json_out_new_root_tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes tbwabcoc
on tbwa.tbamessage_benefitsworkerattributes_val_benefitscurrentorganizationcodes=tbwabcoc.id
left outer join default.json_out_new_root_tbamessage_personattributes tbpa 
on rt.tbamessage_personattributes=tbpa.id left outer join 
json_out_new_root_tbamessage_personattributes_val_additionalattributes tbpavaa
on tbpa.tbamessage_personattributes_val_additionalattributes = tbpavaa.id
left outer join default.json_out_new_root_tbamessage_benefitsworkerattributes_val_benefitscurrentemploymentstatuses tbwabcs
on tbwa.tbamessage_benefitsworkerattributes_val_benefitscurrentemploymentstatuses=tbwabcs.id
